// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repositories

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Attempt struct {
	ID        string       `json:"id"`
	StartTime time.Time    `json:"start_time"`
	EndTime   sql.NullTime `json:"end_time"`
	Status    string       `json:"status"`
}

type Question struct {
	ID            string          `json:"id"`
	Title         string          `json:"title"`
	Difficulty    string          `json:"difficulty"`
	Statement     string          `json:"statement"`
	Constraints   string          `json:"constraints"`
	Examples      json.RawMessage `json:"examples"`
	FuncSignature sql.NullString  `json:"func_signature"`
	TablesSchema  sql.NullString  `json:"tables_schema"`
	QType         string          `json:"q_type"`
}

type Result struct {
	ID              string         `json:"id"`
	AttemptID       string         `json:"attempt_id"`
	QuestionID      string         `json:"question_id"`
	Code            string         `json:"code"`
	Language        string         `json:"language"`
	Passed          bool           `json:"passed"`
	ExecutionTimeMs int32          `json:"execution_time_ms"`
	SubmissionTime  time.Time      `json:"submission_time"`
	OutputLog       sql.NullString `json:"output_log"`
}
