// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repositories

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO attempts (
    id, start_time, status
) VALUES (
    $1, $2, $3
)
RETURNING id, start_time, end_time, status
`

type CreateAttemptParams struct {
	ID        string    `json:"id"`
	StartTime time.Time `json:"start_time"`
	Status    string    `json:"status"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error) {
	row := q.db.QueryRowContext(ctx, createAttempt, arg.ID, arg.StartTime, arg.Status)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
	)
	return i, err
}

const createResult = `-- name: CreateResult :one
INSERT INTO results (
    id, attempt_id, question_id, code, language, passed, execution_time_ms, submission_time, output_log
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, attempt_id, question_id, code, language, passed, execution_time_ms, submission_time, output_log
`

type CreateResultParams struct {
	ID              string         `json:"id"`
	AttemptID       string         `json:"attempt_id"`
	QuestionID      string         `json:"question_id"`
	Code            string         `json:"code"`
	Language        string         `json:"language"`
	Passed          bool           `json:"passed"`
	ExecutionTimeMs int32          `json:"execution_time_ms"`
	SubmissionTime  time.Time      `json:"submission_time"`
	OutputLog       sql.NullString `json:"output_log"`
}

func (q *Queries) CreateResult(ctx context.Context, arg CreateResultParams) (Result, error) {
	row := q.db.QueryRowContext(ctx, createResult,
		arg.ID,
		arg.AttemptID,
		arg.QuestionID,
		arg.Code,
		arg.Language,
		arg.Passed,
		arg.ExecutionTimeMs,
		arg.SubmissionTime,
		arg.OutputLog,
	)
	var i Result
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.QuestionID,
		&i.Code,
		&i.Language,
		&i.Passed,
		&i.ExecutionTimeMs,
		&i.SubmissionTime,
		&i.OutputLog,
	)
	return i, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, start_time, end_time, status FROM attempts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAttempt(ctx context.Context, id string) (Attempt, error) {
	row := q.db.QueryRowContext(ctx, getAttempt, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
	)
	return i, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, title, difficulty, statement, constraints, examples, func_signature, tables_schema, q_type FROM questions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetQuestion(ctx context.Context, id string) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Difficulty,
		&i.Statement,
		&i.Constraints,
		&i.Examples,
		&i.FuncSignature,
		&i.TablesSchema,
		&i.QType,
	)
	return i, err
}

const insertQuestion = `-- name: InsertQuestion :one
INSERT INTO questions (
    id, title, difficulty, statement, constraints, examples, func_signature, tables_schema, q_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, title, difficulty, statement, constraints, examples, func_signature, tables_schema, q_type
`

type InsertQuestionParams struct {
	ID            string          `json:"id"`
	Title         string          `json:"title"`
	Difficulty    string          `json:"difficulty"`
	Statement     string          `json:"statement"`
	Constraints   string          `json:"constraints"`
	Examples      json.RawMessage `json:"examples"`
	FuncSignature sql.NullString  `json:"func_signature"`
	TablesSchema  sql.NullString  `json:"tables_schema"`
	QType         string          `json:"q_type"`
}

func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, insertQuestion,
		arg.ID,
		arg.Title,
		arg.Difficulty,
		arg.Statement,
		arg.Constraints,
		arg.Examples,
		arg.FuncSignature,
		arg.TablesSchema,
		arg.QType,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Difficulty,
		&i.Statement,
		&i.Constraints,
		&i.Examples,
		&i.FuncSignature,
		&i.TablesSchema,
		&i.QType,
	)
	return i, err
}

const listQuestions = `-- name: ListQuestions :many
SELECT id, title, difficulty, statement, constraints, examples, func_signature, tables_schema, q_type FROM questions
ORDER BY title
`

func (q *Queries) ListQuestions(ctx context.Context) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Difficulty,
			&i.Statement,
			&i.Constraints,
			&i.Examples,
			&i.FuncSignature,
			&i.TablesSchema,
			&i.QType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResultsByAttempt = `-- name: ListResultsByAttempt :many
SELECT id, attempt_id, question_id, code, language, passed, execution_time_ms, submission_time, output_log FROM results
WHERE attempt_id = $1
ORDER BY submission_time ASC
`

func (q *Queries) ListResultsByAttempt(ctx context.Context, attemptID string) ([]Result, error) {
	rows, err := q.db.QueryContext(ctx, listResultsByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Result
	for rows.Next() {
		var i Result
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.Code,
			&i.Language,
			&i.Passed,
			&i.ExecutionTimeMs,
			&i.SubmissionTime,
			&i.OutputLog,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttempt = `-- name: UpdateAttempt :exec
UPDATE attempts
SET end_time = $2, status = $3
WHERE id = $1
`

type UpdateAttemptParams struct {
	ID      string       `json:"id"`
	EndTime sql.NullTime `json:"end_time"`
	Status  string       `json:"status"`
}

func (q *Queries) UpdateAttempt(ctx context.Context, arg UpdateAttemptParams) error {
	_, err := q.db.ExecContext(ctx, updateAttempt, arg.ID, arg.EndTime, arg.Status)
	return err
}
