// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repositories

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO attempts (
    id, start_time, status
) VALUES (
    $1, $2, $3
)
RETURNING id, start_time, end_time, status
`

type CreateAttemptParams struct {
	ID        string             `json:"id"`
	StartTime pgtype.Timestamptz `json:"start_time"`
	Status    string             `json:"status"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, createAttempt, arg.ID, arg.StartTime, arg.Status)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
	)
	return i, err
}

const createResult = `-- name: CreateResult :one
INSERT INTO results (
    id, attempt_id, question_id, code, language, passed, execution_time_ms, submission_time, output_log
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, attempt_id, question_id, code, language, passed, execution_time_ms, submission_time, output_log
`

type CreateResultParams struct {
	ID              string             `json:"id"`
	AttemptID       string             `json:"attempt_id"`
	QuestionID      string             `json:"question_id"`
	Code            string             `json:"code"`
	Language        string             `json:"language"`
	Passed          bool               `json:"passed"`
	ExecutionTimeMs int32              `json:"execution_time_ms"`
	SubmissionTime  pgtype.Timestamptz `json:"submission_time"`
	OutputLog       pgtype.Text        `json:"output_log"`
}

func (q *Queries) CreateResult(ctx context.Context, arg CreateResultParams) (Result, error) {
	row := q.db.QueryRow(ctx, createResult,
		arg.ID,
		arg.AttemptID,
		arg.QuestionID,
		arg.Code,
		arg.Language,
		arg.Passed,
		arg.ExecutionTimeMs,
		arg.SubmissionTime,
		arg.OutputLog,
	)
	var i Result
	err := row.Scan(
		&i.ID,
		&i.AttemptID,
		&i.QuestionID,
		&i.Code,
		&i.Language,
		&i.Passed,
		&i.ExecutionTimeMs,
		&i.SubmissionTime,
		&i.OutputLog,
	)
	return i, err
}

const createTest = `-- name: CreateTest :one
INSERT INTO tests (data) VALUES ($1) RETURNING id, created_at, updated_at, data
`

func (q *Queries) CreateTest(ctx context.Context, data []byte) (Test, error) {
	row := q.db.QueryRow(ctx, createTest, data)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Data,
	)
	return i, err
}

const createTestHistory = `-- name: CreateTestHistory :one
INSERT INTO test_history (test_id, questions_solved, total_questions, time_taken_seconds, test_cases_passed, total_test_cases, answers)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, test_id, questions_solved, total_questions, time_taken_seconds, test_cases_passed, total_test_cases, created_at, answers
`

type CreateTestHistoryParams struct {
	TestID           pgtype.UUID `json:"test_id"`
	QuestionsSolved  int32       `json:"questions_solved"`
	TotalQuestions   int32       `json:"total_questions"`
	TimeTakenSeconds int32       `json:"time_taken_seconds"`
	TestCasesPassed  int32       `json:"test_cases_passed"`
	TotalTestCases   int32       `json:"total_test_cases"`
	Answers          []byte      `json:"answers"`
}

func (q *Queries) CreateTestHistory(ctx context.Context, arg CreateTestHistoryParams) (TestHistory, error) {
	row := q.db.QueryRow(ctx, createTestHistory,
		arg.TestID,
		arg.QuestionsSolved,
		arg.TotalQuestions,
		arg.TimeTakenSeconds,
		arg.TestCasesPassed,
		arg.TotalTestCases,
		arg.Answers,
	)
	var i TestHistory
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.QuestionsSolved,
		&i.TotalQuestions,
		&i.TimeTakenSeconds,
		&i.TestCasesPassed,
		&i.TotalTestCases,
		&i.CreatedAt,
		&i.Answers,
	)
	return i, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, start_time, end_time, status FROM attempts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAttempt(ctx context.Context, id string) (Attempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, id)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
	)
	return i, err
}

const getQuestion = `-- name: GetQuestion :one
SELECT id, title, difficulty, statement, constraints, examples, func_signature, tables_schema, q_type FROM questions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetQuestion(ctx context.Context, id string) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestion, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Difficulty,
		&i.Statement,
		&i.Constraints,
		&i.Examples,
		&i.FuncSignature,
		&i.TablesSchema,
		&i.QType,
	)
	return i, err
}

const getTest = `-- name: GetTest :one
SELECT id, created_at, updated_at, data FROM tests WHERE id = $1
`

func (q *Queries) GetTest(ctx context.Context, id pgtype.UUID) (Test, error) {
	row := q.db.QueryRow(ctx, getTest, id)
	var i Test
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Data,
	)
	return i, err
}

const insertQuestion = `-- name: InsertQuestion :one
INSERT INTO questions (
    id, title, difficulty, statement, constraints, examples, func_signature, tables_schema, q_type
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, title, difficulty, statement, constraints, examples, func_signature, tables_schema, q_type
`

type InsertQuestionParams struct {
	ID            string          `json:"id"`
	Title         string          `json:"title"`
	Difficulty    string          `json:"difficulty"`
	Statement     string          `json:"statement"`
	Constraints   string          `json:"constraints"`
	Examples      json.RawMessage `json:"examples"`
	FuncSignature pgtype.Text     `json:"func_signature"`
	TablesSchema  pgtype.Text     `json:"tables_schema"`
	QType         string          `json:"q_type"`
}

func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, insertQuestion,
		arg.ID,
		arg.Title,
		arg.Difficulty,
		arg.Statement,
		arg.Constraints,
		arg.Examples,
		arg.FuncSignature,
		arg.TablesSchema,
		arg.QType,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Difficulty,
		&i.Statement,
		&i.Constraints,
		&i.Examples,
		&i.FuncSignature,
		&i.TablesSchema,
		&i.QType,
	)
	return i, err
}

const listQuestions = `-- name: ListQuestions :many
SELECT id, title, difficulty, statement, constraints, examples, func_signature, tables_schema, q_type FROM questions
ORDER BY title
`

func (q *Queries) ListQuestions(ctx context.Context) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Difficulty,
			&i.Statement,
			&i.Constraints,
			&i.Examples,
			&i.FuncSignature,
			&i.TablesSchema,
			&i.QType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResultsByAttempt = `-- name: ListResultsByAttempt :many
SELECT id, attempt_id, question_id, code, language, passed, execution_time_ms, submission_time, output_log FROM results
WHERE attempt_id = $1
ORDER BY submission_time ASC
`

func (q *Queries) ListResultsByAttempt(ctx context.Context, attemptID string) ([]Result, error) {
	rows, err := q.db.Query(ctx, listResultsByAttempt, attemptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Result
	for rows.Next() {
		var i Result
		if err := rows.Scan(
			&i.ID,
			&i.AttemptID,
			&i.QuestionID,
			&i.Code,
			&i.Language,
			&i.Passed,
			&i.ExecutionTimeMs,
			&i.SubmissionTime,
			&i.OutputLog,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestHistory = `-- name: ListTestHistory :many
SELECT id, test_id, questions_solved, total_questions, time_taken_seconds, test_cases_passed, total_test_cases, created_at, answers FROM test_history WHERE test_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListTestHistory(ctx context.Context, testID pgtype.UUID) ([]TestHistory, error) {
	rows, err := q.db.Query(ctx, listTestHistory, testID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestHistory
	for rows.Next() {
		var i TestHistory
		if err := rows.Scan(
			&i.ID,
			&i.TestID,
			&i.QuestionsSolved,
			&i.TotalQuestions,
			&i.TimeTakenSeconds,
			&i.TestCasesPassed,
			&i.TotalTestCases,
			&i.CreatedAt,
			&i.Answers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTests = `-- name: ListTests :many
SELECT 
    t.id, 
    t.created_at, 
    t.updated_at, 
    t.data->>'title' as title, 
    (t.data->>'time')::int as time,
    h.created_at as last_attempt_date
FROM tests t
LEFT JOIN LATERAL (
    SELECT created_at FROM test_history 
    WHERE test_id = t.id 
    ORDER BY created_at DESC LIMIT 1
) h ON true
ORDER BY t.created_at DESC
`

type ListTestsRow struct {
	ID              pgtype.UUID        `json:"id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Title           interface{}        `json:"title"`
	Time            int32              `json:"time"`
	LastAttemptDate pgtype.Timestamptz `json:"last_attempt_date"`
}

func (q *Queries) ListTests(ctx context.Context) ([]ListTestsRow, error) {
	rows, err := q.db.Query(ctx, listTests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTestsRow
	for rows.Next() {
		var i ListTestsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Time,
			&i.LastAttemptDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttempt = `-- name: UpdateAttempt :exec
UPDATE attempts
SET end_time = $2, status = $3
WHERE id = $1
`

type UpdateAttemptParams struct {
	ID      string             `json:"id"`
	EndTime pgtype.Timestamptz `json:"end_time"`
	Status  string             `json:"status"`
}

func (q *Queries) UpdateAttempt(ctx context.Context, arg UpdateAttemptParams) error {
	_, err := q.db.Exec(ctx, updateAttempt, arg.ID, arg.EndTime, arg.Status)
	return err
}
