-- +goose Up
ALTER TABLE tests ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';
ALTER TABLE tests ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC';
ALTER TABLE test_history ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';
ALTER TABLE attempts ALTER COLUMN start_time TYPE TIMESTAMPTZ USING start_time AT TIME ZONE 'UTC';
ALTER TABLE attempts ALTER COLUMN end_time TYPE TIMESTAMPTZ USING end_time AT TIME ZONE 'UTC';
ALTER TABLE results ALTER COLUMN submission_time TYPE TIMESTAMPTZ USING submission_time AT TIME ZONE 'UTC';

-- +goose Down
ALTER TABLE tests ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'UTC';
ALTER TABLE tests ALTER COLUMN updated_at TYPE TIMESTAMP USING updated_at AT TIME ZONE 'UTC';
ALTER TABLE test_history ALTER COLUMN created_at TYPE TIMESTAMP USING created_at AT TIME ZONE 'UTC';
ALTER TABLE attempts ALTER COLUMN start_time TYPE TIMESTAMP USING start_time AT TIME ZONE 'UTC';
ALTER TABLE attempts ALTER COLUMN end_time TYPE TIMESTAMP USING end_time AT TIME ZONE 'UTC';
ALTER TABLE results ALTER COLUMN submission_time TYPE TIMESTAMP USING submission_time AT TIME ZONE 'UTC';
